name: Java Selenium CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Step 4: Install dependencies and build the project
      - name: Install dependencies
        run: mvn clean install

      # Step 5: Set up Chrome for headless testing
      - name: Set up Chrome for Selenium
        run: sudo apt-get update && sudo apt-get install -y google-chrome-stable

      # Step 6: Run the Selenium test
      - name: Run LoginTest
        run: mvn exec:java -Dexec.mainClass="org.example.LoginTest"

      # Step 7: Archive test results
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/
